---
format:
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - bottom=20mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: "25"
---

<!-- Code for this CV is inspired by Alex Bass (https://alexbass.me/posts/resume/)  -->

```{=tex}
\begin
{huge}\begin{center}{\bf CHEN TANG}\end{center}\end{huge}
\vspace{5pt}
\begin{center}
Kogod School of Business, American University\\
\vspace{3pt}
4400 Massachusetts Avenue, NW, Washington, DC 20016\\
\vspace{3pt}
\href{mailto:chentang@american.edu}{chentang@american.edu}\\
\vspace{3pt}
\href{https://www.american.edu/kogod/faculty/chentang.cfm}{Profile} ∙
\href{https://tangc.net}{Website} ∙
\href{https://www.linkedin.com/in/tangchen/}{LinkedIn}\\
\vspace{3pt}
\textit{(Updated: 12/2023)}
\end{center}
\vspace{5pt}
```
## ACADEMIC EMPLOYMENT

**American University**

-   08/2023-*Present*: Assistant Professor, Kogod School of Business

## **EDUCATION**

### School of Labor and Employment Relations, University of Illinois Urbana-Champaign

-   Ph.D. Human Resources and Industrial Relations, 2023

### School of Psychology and Cognitive Science, East China Normal University

-   M.Ed. Applied Psychology, 2012

-   B.S. Psychology, 2009

## **RESEARCH INTERESTS**

Diversity in HR Management/Personnel Selection (Adverse impact, equal and fair access to employment)

HR Analytics and Machine Learning (Multi-objective optimization, ensemble learning, cross-validation, Bayesian statistics)

Behavioral Ethics (Unethical pro-organizational behavior)

## **HONORS AND AWARDS**

2022: Meredith P. Crawford Fellowship, Human Resources Research Organization (HumRRO)

2022: International Personnel Assessment Council James C. Johnson Student Paper Award

2022: Timothy A. Judge Fellowship, School of Labor and Employment Relations, UIUC

2022: University of Illinois List of [Teachers Ranked as Excellent (Fall 2022)](https://citl.illinois.edu/citl-101/measurement-evaluation/teaching-evaluation/teaching-evaluations-(ices)/teachers-ranked-as-excellent)

2020: University of Illinois List of [Teachers Ranked as Excellent (Fall 2020)](https://citl.illinois.edu/citl-101/measurement-evaluation/teaching-evaluation/teaching-evaluations-(ices)/teachers-ranked-as-excellent)

## **TEACHING EXPERIENCE**

Teaching Assistant, LER 590 DDD (HR Analytics), School of Labor and Employment Relations, UIUC, Fall 2022

Instructor, PSYC 245 (Introduction to Industrial-Organizational Psychology), Department of Psychology, UIUC, Spring 2022

Teaching Assistant, LER 593 (Statistics for graduate students in human resources), School of Labor and Employment Relations, UIUC, Fall 2020

Teaching Assistant, Negotiation, School of Entrepreneurship and Management, ShanghaiTech University, Spring 2016 and Spring 2017

Teaching Assistant, Executive MBA Midterm Module, China Europe International Business School, Spring 2017

\newpage

## **REFEREED JOURNAL PUBLICATIONS**

Tang, C., Chen, Y., Wei, W, & Newman, D. A. (2023). Under pressure: LMX drives employee unethical pro-organizational behavior via threat appraisals. *Journal of Business Ethics*. <https://doi.org/10.1007/s10551-023-05534-6>

Song, Q. C., Tang, C., Newman, D. A., & Wee, S. (2023). Adverse impact reduction and job performance optimization via pareto-optimal weighting: A shrinkage formula and regularization technique using machine learning. *Journal of Applied Psychology, 108*(9), 1461–1485. <https://doi.org/10.1037/apl0001085>

Zhang, N., Wang, M., Xu, H., Koenig, N., Hickman, L., Kuruzovich, J., Ng, V., Arhin, K., Wilson, D., Song, Q. C., Tang, C., Alexander, L., & Kim, Y. (2023). Reducing subgroup differences in personnel selection through the application of machine learning. *Personnel Psychology*, peps.12593. <https://doi.org/10.1111/peps.12593>

Song, Q. C., Shin, H. J., Tang, C., Hanna, A., & Behrend, T. S. (2022). Investigating machine learning's capacity to enhance the prediction of career choices. *Personnel Psychology*, 1-25. <https://doi.org/10.1111/peps.12529>

Newman, D. A., Tang, C., Song, Q. C., & Wee, S. (2022). Dropping the GRE, keeping the GRE, or using GRE-optional admissions? Considering test fairness and Pareto-optimal tradeoffs. *International Journal of Testing*. <https://doi.org/10.1080/15305058.2021.2019750>

Song, Q. C., Tang, C., & Wee, S. (2021). Making sense of model generalizability: A tutorial on cross-validation in R and Shiny. *Advances in Methods and Practices in Psychological Science. 4*(1): 1-17. <https://doi.org/10.1177/2515245920947067>

Yang, Y., Tang, C., Qu, X., Wang, C., & Denson, T. F. (2018). Group facial width-to-height ratio predicts intergroup negotiation outcomes. *Frontiers in Psychology, 9*. <https://doi.org/10.3389/fpsyg.2018.00214>

## **MANUSCRIPTS UNDER REVIEW**

Tang, C., Hickman, L., Song, Q. C., & Alexander III, L. (2nd R&R). \[Details omitted for blind reviewing\]. *Journal of Applied Psychology*.

Song, Q. C., Tang, C., & Wee, S. (1st R&R). \[Details omitted for blind reviewing\]. *Journal of Applied Psychology*.

Lee, S. H., Wei, W., Chen, Y., &Tang, C. (1st R&R). \[Details omitted for blind reviewing\]. *Journal of Occupational and Organizational Psychology.*

Wee, S., Newman, D. A., Song, Q. C., & Tang, C. (1st R&R). \[Details omitted for blind reviewing\]. *Journal of Applied Psychology*.

## **MANUSCRIPTS IN PREPARATION**

Tang, C., Newman, D. A., Song, Q. C., & Wee, S. (to be submitted). Shrinkage of diversity tradeoff curves in personnel selection: A comparison of local validity studies, meta-analysis, Bayes-analysis, and ensemble machine learning.

Tang, C., Zhang. B., Lin. Z., Anglim. J., & Li. J. (to be submitted). Faking detection using item-level machine learning.

Tang, C., Shin, H. J., & Song, Q. C. (writing in progress). Combining machine learning models to improve prediction accuracy: The use of ensemble learning in organizational research and practice.

Tang, C., Song, Q. C., & Hickman, L. (writing in progress). Detecting and avoiding common data leakage issues when using machine learning in organizational research.

Culpepper, S. A. & Tang, C. (model implementation). Rank likelihood for non-normal data in Bayesian multilevel models.

Tang, C., Chen, Y., Song, Q. C., & Newman, D. A. (writing in progress). Valuing diversity in hiring when choosing a predictor weighting method: An extension of Sackett et al. (2017).

Lee, SH., & Tang, C. (data collection). Won't stop searching: Detachment, self-improvement, and job search outcomes.

## **BOOK CHAPTERS/SECTIONS**

Tang, C., & Liu, Y. (forthcoming). Agent-based modeling. In Vancouver, J. B., Wang, M., & Weinhardt, J. M. (eds.), *SIOP Frontiers Series: Computational Modeling for Industrial-Organizational Psychologists*. Washington, DC: American Psychological Association.

Song, Q. C., Liu, M. Q., Tang, C., & Long, L. (2020). Applying principles of big data to the workplace and talent analytics. *Big Data Methods for Psychological Research: New Horizons and Challenges*. Washington D. C., APA books.

Tang, C., & Yang, Y. (2017). Goals. In Zeigler-Hill, V., & Shackelford, T. K. (Eds.) *Encyclopedia of Personality and Individual Difference*. Springer.

## **CONFERENCE PRESENTATIONS**

Tang, C. (Co-Chair), Song, Q. C. (Co-Chair) & Wee, S (Co-Chair). (2024). *Multi-Objective Optimization 5.0: Applications in the Workplace*. \[Symposium\]. Society for Industrial and Organizational Psychology, Chicago, IL, United States.

Vancouver, J.B., Braun, M., Grand, J., Hardy, J. H., III, Kennedy, D., Neal, A., Tang, C., Wang, M., Weinhardt, J. M., & Zhou, L. (2024, April). *SIOP Frontiers Book on Computational Modeling for I-O Psychologists: Meet the Authors.* \[Symposium\]. Society for Industrial and Organizational Psychology, Chicago, IL, United States.

Song, Q. C. (Co-Chair) & Tang, C. (Co-Chair). (2023). *Multi-Objective Optimization 4.0: Applications in Personnel Selection.* \[Symposium\]. Society for Industrial and Organizational Psychology Annual Conference, Boston, MA.

Tang, C., Newman, D. A., Song, Q. C. & Wee, S. (July 2022). *Shrinkage of diversity tradeoff curves in personnel selection: A comparison of local validity studies, meta-analysis, Bayes-analysis, and ensemble machine learning* \[Invited presentation; Winner of the James C. Johnson Student Paper Award\]. The 2022 Annual Conference of the International Personnel Assessment Council, San Diego, CA.

Tang, C., Newman, D. A., Song, Q. C. & Wee, S. (April 2022). Shrinkage of diversity tradeoff curves in personnel selection: A comparison of local validity studies, meta-analysis, and empirical Bayes-analysis. In Song, Q. C., & Wee, S. (Co-Chairs), *Multi-Objective Optimization in the Workplace 3.0: Advancing research on adverse impact in personnel selection* \[Symposium paper\]. 37th Annual Conference of the Society for Industrial and Organizational Psychology, Seattle, WA.

Song, Q. C., Shin, H. J., Tang, C., Hanna, A. & Behrend, T. S., (April 2022). Machine learning enhances the prediction of career choices. In Chris Nye (Chair), *The power of vocational interests: Understanding choices, attitudes, and behavior* \[Symposium paper\]. 37th Annual Conference of the Society for Industrial and Organizational Psychology, Seattle, WA.

Tang, C. (June 2021). *Common data leakage issues when using machine learning in organizational research* \[Talk\]. Technology and Measurement Around the Globe. (Purdue University, West Lafayette, IN. Online Conference)

Lee, SH., Tang, C., Wei, W., & Chen, Y. (August 2021). *The Roles of Compassion and Resilience on Employee Thriving, Well-being, and Interpersonal Deviance* \[Paper\]. 81st Annual Meeting of the Academy of Management. (Online Conference)

Tang, C., Hickman, L., Song, Q. C., & Alexander III, L. (April 2021). *Comparing Item-Level and Scale-Level Predictive Models: A Simulation* \[Poster\]. 36th Annual Convention of the Society for Industrial and Organizational Psychology, New Orleans, LA. (Online Conference)

Tang, C., Newman, D. A., Song, Q. C., & Wee., S. (April 2021). Pareto-Optimal Tradeoffs for Three Notions of Test Fairness. In Song, Q. C. (Chair), *Multi-Objective Optimization in the Workplace 2.0: Applications in Selectio*n \[Symposium paper\]. 36th Annual Convention of the Society for Industrial and Organizational Psychology, New Orleans, LA. (Online Conference)

Tang, C., Chen, Y., Wei, W. (August 2020). *External work locus of control and unethical pro-organizational behavior: A dual-path model* \[Paper\]. 80th Annual Meeting of the Academy of Management, Vancouver, British Columbia, Canada. (Online Conference)

Tang, C., Newman, D. A., & Song, Q. C. (April 2020). Addressing diversity-validity tradeoffs via Pareto weights with orthogonalized criteria. In Song, Q. C. & Wee. S. (Co-chairs), *Multi-Objective Optimization in the Workplace: Addressing Adverse Impact in Selection* \[Symposium paper\]. 35th Annual Convention of the Society for Industrial and Organizational Psychology, Austin, TX. (Online Conference)

Song, Q. C., & Tang, C. (April 2020). Adverse impact reduction for multiple subgroups: A Pareto-optimization approach. In Song, Q. C. & Wee. S. (Co-chairs), *Multi-Objective Optimization in the Workplace: Addressing Adverse Impact in Selection* \[Symposium paper\]. 35th Annual Convention of the Society for Industrial and Organizational Psychology, Austin, TX. (Online Conference)

Tang, C., Shin, H. J., Barve, A., & Song, Q., C. (April 2020). *Using ensemble machine learning to improve assessment in personnel selection* \[Poster\]. 35th Annual Convention of the Society for Industrial and Organizational Psychology, Austin, TX. (Online Conference)

Lee, S. H., Tang, C., & Liang, Y. J. (April 2020). *Won't stop searching: Detachment, self-improvement, and job search outcomes* \[Poster\]. 35th Annual Convention of the Society for Industrial and Organizational Psychology, Austin, TX. (Online Conference)

Tang, C., Chen, Y., Song, Q. C., & Newman, D. A. (April 2019). *Predictor weighting with adverse impact and shrinkage: Reply to Sackett et al. (2017)* \[Poster\]. 34th Annual Convention of the Society for Industrial and Organizational Psychology, Washington, DC.
